const express = require('express')
const cors = require('cors');
require(`dotenv`).config()
const mongoose = require(`./db_connection/dbConnection`)
const auth = require(`./collections/auth`)
const user = require(`./collections/user_api`)
const product = require('./collections/product_api')
const cart = require('./collections/cart_api')
const order = require('./collections/order_api')
const app = express()
const port = process.env.port || 8000
app.use(express.json())
app.use(cors({ origin: true, credentials: true }))
app.use(`/auth`, auth)
app.use(`/user`, user)
app.use(`/product`, product)
app.use(`/cart`, cart)
app.use(`/order`, order)
app.listen(port, () => console.log(`server is running ar ${port}`))
